### ISSUE TITLE
duplicated code

### ISSUE THREAD

**Issue by igorlima** [igorlima/js-type-gen#4]
duplicated properties in package.json

look for a way to clean up this. `generator-js-type` is declared twice.

see above a snapshot.

``` js
{
  "dependencies": {
    "generator-js-type": "0.0.3"
  },
  "scripts": {
    "preinstall": "npm i -g yo generator-js-type@0.0.3"
  }
}
```

**Comment by schweller** [comment]
Here is some guidance:

https://github.com/YWebCA/ywca-cli/blob/master/index.js

**Comment by igorlima** [comment]
Already done: #13 

Commit id: https://github.com/igorlima/js-type-gen/commit/43430999340ae9d0a5a4c4dca7da42d04e9d54dd
